### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by coolerooney** [pinski1/dSMD#1]
Hi Pinski

like your work,think the 6470 is undervalued, but also a bitch to get set up properly!

Looking for Arduino flavour code+ board

can you help

thx

coolerooney

**Comment by pinski1** [comment]
coolerooney,

Aside from googling "L6470" and getting:
https://www.sparkfun.com/products/10859
http://forums.netduino.com/index.php?/topic/4582-spiconfiguration-and-l6470-stepper-driver/
https://www.tindie.com/products/ElectricLaboratory/chainable-intelligent-stepper-driver-l6470/

Not really. I've not yet had a chance to even get the dSMD produced let
alone tested so I have no code to speak of.

Regards,

Robert K.
